### PR TITLE
Massive performance improvement: new chunk allocation system

### PR DESCRIPTION
**Pull request by shwestrick**
This patch completely re-implements the chunk allocation subsystem, inspired in part by the [Hoard](https://github.com/emeryberger/Hoard) algorithm. Below are the percent differences against `mpl/master` on 70 processors, for 20 back-to-back runs of each benchmark. The results are impressive, to say the least. The new system is typically both faster and more space-efficient, in some cases by a wide margin: up to 30% improvement in time, and up to 90% improvement in space. The numbers speak for themselves:

Screen Shot 2021-03-16 at 2 14 34 PM

This implementation is certainly not "finished", and there are a couple sore thumbs above. But IMO these results are already *so much better* than the prior design, that it's worth pushing onto master. I'm really glad to get rid of the prior design (implemented by me a few years ago 😬), which was largely unprincipled and clearly has been secretly holding us back this whole time!

Some notes about the results:
  * The space improvements on `ocaml-binarytrees5` and `ocaml-lu-decomp` easily outweigh the slight increase in time.
  * ~For `dedup` and `ocaml-mandelbrot`, these appear to be somewhat affected by the "megablocks" mechanism which I describe below. Megablocks are configurable, and it turns out that I'm able to completely eliminate these overheads by decreasing the `megablock-threshold`. This is a tradeoff, of course.~ **EDIT**: I'm now pretty sure this has nothing to do with the megablocks. In a larger experiment, the new design wins across the board on these benchmarks. See the [comment below](https://github.com/MPLLang/mpl/pull/135#issuecomment-801452474).

New algorithm details
-----------------
Recall that each heap chunk is one or more contiguous **blocks** (where a block is typically one OS page). In the new design, blocks are allocated from the OS in contiguous groups called **superblocks**. Each superblock contains 2^X blocks, configurable at runtime via `@mpl superblock-threshold X --`. Each superblock is assigned a **size-class** K which indicates that it will only supply allocations of 2^K blocks. When we allocate a chunk, we round up to the nearest power-of-2 number of blocks and search for a superblock of the appropriate size. If no such superblock is available, new superblocks are `mmap`ed from the OS.

Each processor maintains a local list of superblocks. When a chunk is freed, we send that chunk back to the processor that owns the superblock which contains the chunk. ("Sending" a free chunk is implemented by pushing onto a concurrent stack owned by the other processor. Each processor periodically clears out its own stack of freed chunks.) When a superblock becomes "completely empty" (i.e. none of its blocks are currently in use), it can be recycled for any size-class.

The local freelists of each processor are sorted into "fullness groups" to ensure two things.
1. An appropriate superblock can always be found in O(1) time by skipping the "completely full" group.
2. New allocations target "nearly full" superblocks as much as possible, to encourage "nearly empty" superblocks to become completely empty and therefore reusable in any size class.

So, overall this largely mimics the Hoard algorithm, but is different in a few ways:
  - For especially large allocations (bigger than the superblock-threshold), Hoard would tell us to just use `mmap`/`munmap` directly. However in our setting, I found that this doesn't perform very well. (I don't think these functions are at all parallel.) So, I implemented a separate system for large allocations, which I call **megablocks**. Free megablocks are stored in a global size-classed freelist. For really, *really*, **really** large allocations, we use `mmap`/`munmap` directly. This threshold is controllable at runtime via `@mpl megablock-threshold X --` (any free megablock of size at least 2^X is unmapped). Note that by setting `megablock-threshold` equal to the `superblock-threshold`, we can bypass the megablock system entirely, if desired, and recover the Hoard behavior.
  - Our processor-local superblocks are not concurrently accessible by other processors. All frees are performed via message passing between processors, as described above.
  - We currently don't have any mechanism for sharing nearly-empty superblocks amongst processors. (Hoard uses a single "global" heap to accomplish this.) Therefore, technically the memory requirement in our current design can require as much as a factor-P more memory. **This is something which we need to investigate more going forward.**

### CODE REVIEW

**Comment by shwestrick** [comment]
@typerSniper any thoughts? Should we go ahead and merge?

**Comment by shwestrick** [comment]
Some notes from today's meeting. Ideas for future improvements.

Amortizing cost of `mmap`:
  - In the current design, when a new superblock is needed, we don't allocate just one new superblock. Instead, we allocate N superblocks in one go, where N is some fixed granularity. This helps amortize the cost of mmap (especially when many processors are allocating in parallel) and in my experiments seemed to have a large impact.
  - However, using a fixed granularity still can't guarantee provably low contention.
  - Instead, we should consider doing an **exponential ramp-up** (for example: on each`mmap`, allocate twice as much memory as the previous).
  - This will definitely improve runtimes, but at some space penalty. The question is: do we still get bounded fragmentation?

Proper size-classing for megablocks.
  - At the moment, megablocks are as small as they possibly can be, and the "size-classes" for megablocks are just lower-bounds on their size.
  - This is doesn't necessary play nice with reusing megablocks. For example, if we needed a megablock of size 2^15 - 1, currently we would begin by looking in the bucket with a lower-bound of 2^14 and then, if we don't find anything, look in the bucket of lower bound 2^15. So, in the worst case, we might need to inspect an unbounded number of megablocks.
  - If we switch to doing "proper" size-classing for megablocks, by **rounding up each allocated megablock to the nearest power-of-2**, we regain O(1) megablock search.

Implementing sharing of superblocks between processors.
  - We *could* do Hoard-style locking of superblocks/etc... but it would be nice to have a lock-free algorithm instead. 
  - Currently, we free blocks by sending messages to the owner of the superblock. To support moving superblocks between processors, we need to be able to **re-route messages**. (Why? Suppose a superblock begins a transition from proc A to proc B. Some other proc C might attempt to free a block by sending a message to A. Now, A needs to resend that message to B.)
  - Seems pretty nice!
  - One last problem: if we want to use a "global" space to facilitate Hoard-style sharing, then some superblocks may not be owned by *any* processor. Who then should receive messages to a free a block in such a superblock? We can manage this by "putting these messages aside" until the superblock becomes owned by a processor. Specifically, imagine sending these messages to the superblock itself, and then clear out the messages as soon as the superblock becomes owned by a specific processor.

**Comment by shwestrick** [comment]
Looking a bit more into the apparent overheads on `dedup` and `ocaml-mandelbrot`, I did a larger experiment: 100 runs back-to-back. On this experiment, we get much better results.

| Benchmark | Time | Space |
|---|---|---|
| `ocaml-mandelbrot` | -1% | -47% |
| `dedup` | -14% | -47% | 

Some analysis:
  - `ocaml-mandelbrot` has a very small working-set size. The initial memory requirement of the new chunk allocator appears to be slightly higher than the old design. This is why on the smaller experiment, there was an increased memory requirement. On the larger experiment, the new design begins to shine as it recycles memory much more effectively. This results in less memory usage.
  - `dedup` appears to be a bit sensitive to the precise timing of root CCs, which are non-deterministic, and each fairly long (there are lots of heap objects to trace in this benchmark). On the larger experiment, we see a more clear indication of the "steady state". And we see that once again, the new design outperforms the old significantly.

**Comment by umutacar** [comment]
Niiice!  I thought we came up with a good term for super/mega chunk/block etc. What was it?

**Comment by umutacar** [comment]
I remember now: COMB contiguous memory block

**Pull request merged**
