### PR TITLE
Concurrent merge

### PR DESCRIPTION
**Pull request by typerSniper**
Hey Sam, 

I've checked the CC code on all our standard benchmarks. It runs without errors.

Please take a look and let me know if you find something off.

### CODE REVIEW

**Comment by shwestrick** [comment]
Great! I'll do some testing today and tomorrow.

**Comment by shwestrick** [comment]
I'm getting what look like debugging messages (see also the screen shot).
```
FORCE  [P02|CC_addToStack]: Concurrent Stack is not initialised
```
Are these a bug? Or, if these are harmless, can we remove the message?

Screen Shot 2020-12-14 at 5 21 25 PM

**Comment by typerSniper** [comment]
Right, this is not a bug. I removed it but not properly.


- Jatin

**Comment by shwestrick** [comment]
I did some testing overnight and haven't found any problems. The performance looks good.

I made some aesthetic changes and removed warnings during compilation (00dc6de9e0326e31312f2bc2a4b5b7605fbac2c7).

Let me know if you think everything looks good. If so, I think we're ready to merge.

**Pull request merged**
