### PR TITLE
Function inlining attributes

### PR DESCRIPTION
**Pull request by MatthewFluet**
Propagate inlining attributes on functions and applications from front-end through SSA2 IR.

### CODE REVIEW

**Comment by MatthewFluet** [comment]
The syntax for inlining annotations is the following:

```sml
val f = fn __inline_always__ x => x

val g = fn __inline_never__ true  => false
                          | false => true

val rec even = fn __inline_always__ 0 => true
                                  | n => odd (n - 1)
    and odd  = fn __inline_never__  0 => false
                                  | n => even (n - 1)

fun __inline_always__ fast x y z = if x then y else slow (z, y)
and __inline_never__ slow (true,  y) = fib y
                   | slow (false, y) = fast (isPrime y, y, isSquare y)

val res = __inline_always__ foo x

val res = __inline_never__ bar y
```

Note that a curried `fun` declaration passes the inlining annotation to all of the implicit functions; for example, the `fast`/`slow` above is equivalent to:
```sml
val rec fast = fn __inline_always__ x => 
               fn __inline_always__ y =>
               fn __inline_always__ z => if x then y else slow (z, y)
and slow = fn __inline_never__ (true,  y) => fib y
                             | (false, y) => fast (isPrime y, y, isSquare y)
```

Similarly, a "flat application" passes the inlining annotation to all of the implicity binary applications; for example
```sml
val res = __inline_always__ f x y z
```
becomes
```sml
val res = __inline_always__ (__inline_always__ (__inline_always__ f x) y) z
```

A "flat application" is the way that the source code of an application is parsed, in order to properly resolve infix operators; for example:
```sml
val res = __inline_always__ f x + z
```
becomes
```sml
val res = __inline_always__ (op+) (__inline_always__ f x, z)
```

Syntax is a little clumsy for mutually recursive functions and functions with multiple clauses/matches, but it probably suffices for the common case(s).

**Comment by MatthewFluet** [comment]
The SSA inlining passes have not been fully updated to properly obey the inlining annotations.  In particular, the current implementation of inlining assumes that if a function is a candidate for inlining (due to the size threshhold), then it is inlined everywhere and the function can be dropped from the program; this "breaks" if a function that is a candidate for inlining is not inlined at a `__inline__never__` call site.

I'm thinking that the best approach is to fix the current `inlineLeaf` and `inlineNonRecursive` passes to properly handle the `__inline_never__` annotation on call sites and then add a new `inlineAlways` pass to run after (or before?) `inlineNonrecursive` to hande the `__inline_always__` annotations.

**Comment by MatthewFluet** [comment]
I've fixed the `inlineLeaf` and `inlineNonRecursive` passes to properly handle the `__inline_never__` annotations and also updated the `inlineNonRecursive` pass to properly handle the `__inline_always__` annotation.

**Comment by colin-mcd** [comment]
This looks awesome Matthew! Thanks, should be super helpful

**Comment by MatthewFluet** [comment]
One thing that we didn't discuss: there are implicit calls introduced in `closureConversion` when implementing the higher-order `spork` primitive with SSA's `Spork`/`Spoin`.  Right now, such calls are annotated `InlineAttr.Auto`, but we could consider making them `InlineAttr.Always`/`InlineAttr.never`, but that could probably also be handled by adding `__inline_always__`/`__inline_never__` to the definitions of `cont'`, `spwn'`, `seq'`, and `sync'` in `fun spork` of `Scheduler.sml`.

**Comment by colin-mcd** [comment]
Yeah, I think for now we can just annotate the `cont'`/`spwn'`/`seq'`/`sync'` functions as you said; I expect that should cover all the functionality we want, hopefully!

**Pull request merged**
